### ISSUE TITLE
Integración del bot con Gmail

### ISSUE THREAD

**Issue by marvenegas98** [Hilary1232/Francis-el-asistente-del-curso#4]
Como uno de los casos de uso del software, se encuentra la notificación de respuestas mediante Gmail. Para esto, se debe habilitar el bot para enviar un correo al administrador mediante Gmail, cada vez que el bot envíe un mensaje. 
Esta tarea incluye:
1.  Recuperar el correo del administrador desde la base de datos **(Tabla usuarios, ver ejemplo de conexión en get-cursos de app.py).** 
2.  Habilitar el bot para enviar un mensaje al correo del administrador (recuperado de la base), justo después de responder un mensaje a través de Telegram. La llamada a la función que realice este proceso debe encontrarse en la función send_message del archivo **bot.py**, antes de retornar response.

**Comment by Hilary1232** [comment]
Se hizo un nuevo branch llamado "develop2" que es una versión nueva de lo que se tenía anteriormente, por lo que se hizo por aparte ya que se cambiaron muchas cosas
Para la próxima iteración queda pendiente:
- Quitar el gmail alambrado para la persona que envía el correo
