### ISSUE TITLE
Ventana de usuario

### ISSUE THREAD

**Issue by marvenegas98** [Hilary1232/Francis-el-asistente-del-curso#6]
A pesar que al momento ambas aplicaciones funcionan de manera separada, futuramente se integrarán entre ellas. Por lo tanto, es necesario crear la ventana de perfil de usuario.

Esta tarea incluye:

1. Crear un ícono en la esquina superior derecha de la ventana Home (y en todas las ventanas de interfaz, **excepto index.html**) el cual, al ser presionado dirija automáticamente a una ventana de Perfil de Usuario. 
2. Crear una ventana de perfil de usuario. Esta deberá contener los siguientes datos:

- Nombre del usuario

- Correo del usuario (Gmail, ya que es el mismo correo al cual se le harán llegar las notificaciones)

- Nombre del Bot(s) que administra (Puede quedar predeterminado como Francis). 

Todos estos campos deberán ser editables para el usuario desde la interfaz, de tal manera que al cambiar el correo, también se actualice el correo del usuario en la base de datos y el bot funcione correctamente al enviar correos al nuevo correo recuperado de la base. 

Se recomienda seguir el estilo de encabezado de página que ya contienen las demás páginas realizadas al momento.

**Comment by Hilary1232** [comment]
Se hizo un nuevo branch llamado "develop2" que es una versión nueva de lo que se tenía anteriormente, por lo que se hizo por aparte ya que se cambiaron muchas cosas
Para la próxima iteración queda pendiente:
- Agregar el nombre del Bot al perfil de usuario
- Arreglar la interfaz de index.html que se desacomodó
- Agregar el ícono de Francis
- Quitar de las pantallas la opción de cargar/descargar un .csv ya que solo debería ir en home.html
