### ISSUE TITLE
Lectura y edición de archivos csv desde el sistema administrador

### ISSUE THREAD

**Issue by marvenegas98** [Hilary1232/Francis-el-asistente-del-curso#8]
Como uno de los casos de uso de la aplicación, se encuentra la lectura y edición de los guiones desde el sistema administrador, los cuales se encuentran en formato csv. 

Esta tarea incluye: 

- Permitir la selección de un guión
- Abrir el guión para desplegar su contenido
- Permitir edición directa sobre el guión

Estas funcionalidades deben encontrarse en el archivo app.py, o un nuevo archivo en caso de ser demasiado extenso. Siempre y cuando funcione de manera correcta para el usuario desde la interfaz y se conecte con los demás componentes de la aplicación.

**Comment by Hilary1232** [comment]
Esta implementación se hizo con google sheets y permite elegir cualquier archivo csv y editarlo directamente, actualizando su contenido en la página principal para ser visualizada
